---
- name: install and start apache
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    http_port: 80
    max_clients: 200
  become: yes
  tasks:
    - name: install httpd
      apt: 
        package: apache2 
        state: latest

    - name: write the apache config file     
      template: 
        src: templates/httpd.j2 
        dest: /tmp/httpd.conf

    - name: start httpd
      service: 
        name: httpd 
        state: running