---
- name: Deploy VM
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a virtual machine
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        folder: ansible
        datacenter: OUT-SITE
        name: testvmdamien
        template: template_debian12_ansible
        state: poweredon
        esxi_hostname: 10.220.211.101
        disk:
          - size_gb: 10
            type: thin
            datastore: OUT-SITE_TST
        hardware:
          memory_mb: 1024
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: "520"
      delegate_to: localhost
      register: deploy_vm

    - name: Print debug message
      debug:
        msg: "{{ deploy_vm.instance['hw_eth0'].ipaddresses[0] }}"


    - name: Add all instance public IPs to dynamic host group
      add_host: hostname={{ deploy_vm.instance['hw_eth0'].ipaddresses[0] }} groups=vmwarevms
      
      

- name: install and start apache
  hosts: vmwarevms
  gather_facts: yes
  become: yes
  tasks:
    - name: install httpd
      apt:
        package: apache2
        state: latest