---
- name: install and start apache
  hosts: srv01
  connection: local
  vars:
    http_port: 80
    max_clients: 200
  become_user: root
  tasks:
    - name: install httpd
      ansible.builtin.apt: pkg=httpd state=latest


    - name: install httpd
      apt: pkg=httpd state=latest

    - name: write the apache config file
      template: src=httpd.j2 dest=/tmp/httpd.conf

    - name: start httpd
      service: name=httpd state=running


