---
- name: Deploy VM
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a virtual machine
      vmware_guest:
        validate_certs: false
        folder: ansible
        datacenter: OUT-SITE
        name: "{{ vm_name }}"
        template: template_debian12_ansible
        state: poweredon
        guest_id: debian10_64Guest
        esxi_hostname: 10.220.211.101
        disk:
          - size_gb: 10
            type: thin
            datastore: OUT-SITE_TST
        hardware:
          memory_mb: 1024
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: Production2
      delegate_to: localhost
      register: deploy_vm


